Jovana UserServiceTests
djordjeMalkier/banka-core pull request #3
Opened 2022-12-27 11:33 UTC by jovanazivkovic99

2022-12-27 11:48 UTC, daviddimic approved these changes

2022-12-27 11:59 UTC, jovana-velickov commented on src/test/java/common/bankarskiSistem/unit/service/UserServiceUnitTest.java
> +    public void payIn_whenPayInBankAccount_thenReturnBankBalance(User user, BankAccount bankAccount) throws EntityNotFoundException {
vrednosti bi trebale biti prosledjene kao parametri?

2022-12-27 12:02 UTC, jovana-velickov requested changes
.

2022-12-27 12:34 UTC, tamirzad commented on src/test/java/common/bankarskiSistem/unit/service/UserServiceUnitTest.java
> +    public void payIn_whenPayInBankAccount_thenReturnBankBalance(User user, BankAccount bankAccount) throws EntityNotFoundException {
ove vrednosti i ne bas

2022-12-27 13:48 UTC, kyuubi98 approved these changes

2022-12-28 08:12 UTC, jovana-velickov approved these changes

2022-12-28 08:24 UTC, merged